name: My First Workflow
on: 
  push: 
    branches:
jobs: 
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: Simulate a fail
      run: exit 1
    - name: echo the current branch
      run: echo ${{github.ref_name }}

  test_and_deploy:
    steps:
    - name: Checkout the source
      uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2
    - name: Run test
      run: mvn clean test